#!/bin/sh

find . -name '*.rs' | while read FILE; do
    TARGET=$(echo "${FILE}" | sed 's|./src/\([^/\.]*\)[^:]*|\1|')
    if [ "${TARGET}" == "euler" ]; then
        echo '$(call debugexe,euler): '"${FILE}"
        echo '$(call releaseexe,euler): '"${FILE}"
        echo '$(call testexe,euler): '"${FILE}"
    else
        echo '$(call debuglib,'"${TARGET}"'): '"${FILE}"
        echo '$(call releaselib,'"${TARGET}"'): '"${FILE}"
        echo '$(call testexe,'"${TARGET}"'): '"${FILE}"
    fi
    sed -n -e '/extra/!s| *extern  *mod  *\(.*\) *;$|\1|p' ${FILE} | while read CRATE; do
        if [ "${TARGET}" == "euler" ]; then
            echo '$(call debugexe,euler): $(call debuglib,'"${CRATE}"')'
            echo '$(call releaseexe,euler): $(call releaselib,'"${CRATE}"')'
            echo '$(call testexe,euler): $(call debuglib,'"${CRATE}"')'
        else
            echo '$(call debuglib,'"${TARGET}"'): $(call debuglib,'"${CRATE}"')'
            echo '$(call releaselib,'"${TARGET}"'): $(call releaselib,'"${CRATE}"')'
            echo '$(call testexe,'"${TARGET}"'): $(call debuglib,'"${CRATE}"')'
        fi
    done
done | sort -u
