#!/usr/bin/env python3

import sys, glob, os, re

def main():
    if len(sys.argv) < 2:
        print("invalid args", file=sys.stderr)
        print("Usage: %s dirname" % sys.argv[0], file=sys.stderr)
        sys.exit(1)

    mods = [ re.sub(r'.+/prob(\d+)\.rs$', r'prob\1', file)
             for dir in sys.argv[1:] for file in glob.glob("%s/prob*.rs" % dir) ]
    mods.sort()

    for mod in mods:
        print("extern mod %s;" % mod)
    print("")
    print("priv use common::problem::{ Problem };")
    print("")
    print("pub static problems: &'static [&'static Problem<'static>] = &[")
    print(",\n".join(['    &' + mod + '::problem' for mod in mods]))
    print("];")

    sys.exit(0)

if __name__ == '__main__':
    main()

