#!/bin/sh

CRATE_TYPE=$1
CRATE_NAME=$2
MAIN_SRC=$3
shift
shift
ALL_SRC=$@

if [ "${CRATE_TYPE}" == "BIN" ]; then
    echo "debug: \$(DEBUG_${CRATE_NAME})"
    echo "release: \$(RELEASE_${CRATE_NAME})"
fi
if grep -q '#\[test\]' ${ALL_SRC} ; then
    echo "test: run-test-${CRATE_NAME}"
fi
if grep -q '#\[bench\]' ${ALL_SRC} ; then
    echo "bench: run-bench-${CRATE_NAME}"
fi

echo ".PHONY: debug-${CRATE_NAME} release-${CRATE_NAME} test-${CRATE_NAME} run-test-${CRATE_NAME}"
echo "debug-${CRATE_NAME}: \$(DEBUG_${CRATE_NAME})"
echo "release-${CRATE_NAME}: \$(RELEASE_${CRATE_NAME})"
echo "debug-${CRATE_NAME}test: \$(DEBUG_${CRATE_NAME}test)"
echo "release-${CRATE_NAME}test: \$(RELEASE_${CRATE_NAME}test)"
echo "run-test-${CRATE_NAME}: \$(DEBUG_${CRATE_NAME}test)"
echo "	\$(call RUN_TEST,$<)"
echo "run-bench-${CRATE_NAME}: \$(RELEASE_${CRATE_NAME}test)"
echo "	\$(call RUN_BENCH,$<)"

sed -n -e '/extra/!s| *extern  *mod  *\(.*\) *;$|\1|p' ${ALL_SRC} | while read DEP_NAME; do
    echo "\$(DEBUG_${CRATE_NAME}): \$(DEBUG_${DEP_NAME})"
    echo "\$(RELEASE_${CRATE_NAME}): \$(RELEASE_${DEP_NAME})"
    echo "\$(DEBUG_${CRATE_NAME}test): \$(DEBUG_${DEP_NAME})"
    echo "\$(RELEASE_${CRATE_NAME}test): \$(RELEASE_${DEP_NAME})"
done

echo "\$(DEBUG_${CRATE_NAME}): ${ALL_SRC}"
echo "	\$(call DEBUG_${CRATE_TYPE},$<)"
echo "\$(RELEASE_${CRATE_NAME}): ${ALL_SRC}"
echo "	\$(call RELEASE_${CRATE_TYPE},$<)"
echo "\$(DEBUG_${CRATE_NAME}test): ${ALL_SRC}"
echo "	\$(call DEBUG_TEST,$<)"
echo "\$(RELEASE_${CRATE_NAME}test): ${ALL_SRC}"
echo "	\$(call RELEASE_TEST,$<)"
