#!/bin/bash

CRATE_TYPE=$1
CRATE_NAME=$2
MAIN_SRC=$3
shift; shift
ALL_SRC=$@

DEBUG_TARGET="\$(DEBUG_${CRATE_NAME})"
RELEASE_TARGET="\$(RELEASE_${CRATE_NAME})"
DEBUG_TEST="\$(DEBUG_${CRATE_NAME}test)"
RELEASE_TEST="\$(RELEASE_${CRATE_NAME}test)"

if [ "${CRATE_TYPE}" == "BIN" ]; then
    echo "debug: ${DEBUG_TARGET}"
    echo "release: ${RELEASE_TARGET}"
fi
if grep -q '#\[test\]' ${ALL_SRC} ; then
    echo "test: run-test-${CRATE_NAME}"
fi
if grep -q '#\[bench\]' ${ALL_SRC} ; then
    echo "bench: run-bench-${CRATE_NAME}"
fi

cat <<EOF
.PHONY: debug-${CRATE_NAME} release-${CRATE_NAME} test-${CRATE_NAME} run-test-${CRATE_NAME} run-bench-${CRATE_NAME}
debug-${CRATE_NAME}: ${DEBUG_TARGET}
release-${CRATE_NAME}: ${RELEASE_TARGET}
debug-${CRATE_NAME}test: ${DEBUG_TEST}
release-${CRATE_NAME}test: ${RELEASE_TEST}
run-test-${CRATE_NAME}: ${DEBUG_TEST}
	\$(call RUN_TEST,$<)
run-bench-${CRATE_NAME}: ${RELEASE_TEST}
	\$(call RUN_BENCH,$<)
EOF

sed -n -e '/extra/!s| *extern  *mod  *\(.*\) *;$|\1|p' ${ALL_SRC} | while read DEP_NAME; do
    cat <<EOF
${DEBUG_TARGET}: \$(DEBUG_${DEP_NAME})
${RELEASE_TARGET}: \$(RELEASE_${DEP_NAME})
${DEBUG_TEST}: \$(DEBUG_${DEP_NAME})
${RELEASE_TEST}: \$(RELEASE_${DEP_NAME})
EOF
done

cat <<EOF
${DEBUG_TARGET}: \$(ALL_SRC_${CRATE_NAME})
	\$(call DEBUG_${CRATE_TYPE},$<)
${RELEASE_TARGET}: \$(ALL_SRC_${CRATE_NAME})
	\$(call RELEASE_${CRATE_TYPE},$<)
${DEBUG_TEST}: \$(ALL_SRC_${CRATE_NAME})
	\$(call DEBUG_TEST,$<)
${RELEASE_TEST}: \$(ALL_SRC_${CRATE_NAME})
	\$(call RELEASE_TEST,$<)
EOF
