#!/bin/bash

PRINT_CRATE() {
    find ./src -maxdepth 1 -mindepth 1 -name "*.rs" -type f | sort | while read MAIN_SRC; do
        CRATE_NAME=$(rustc --crate-name "${MAIN_SRC}")
        echo RLIB ${CRATE_NAME} ${MAIN_SRC}
    done
    find ./src -mindepth 2 -name "lib.rs" -type f | sort | while read MAIN_SRC; do
        CRATE_NAME=$(rustc --crate-name "${MAIN_SRC}")
        OTHER_SRC=$(echo $(find "$(dirname ${MAIN_SRC})" -name "*.rs" -not -name "lib.rs" -type f))
        echo RLIB ${CRATE_NAME} ${MAIN_SRC} ${OTHER_SRC}
    done
    find ./src -mindepth 2 -name "main.rs" -type f | sort | while read MAIN_SRC; do
        CRATE_NAME=$(rustc --crate-name "${MAIN_SRC}")
        OTHER_SRC=$(echo $(find "$(dirname ${MAIN_SRC})" -name "*.rs" -not -name "main.rs" -type f))
        echo BIN ${CRATE_NAME} ${MAIN_SRC} ${OTHER_SRC}
    done
}

PRINT_DEFINE_INCLUDE() {
    local CRATE_TYPE=$1
    local CRATE_NAME=$2
    local MAIN_SRC=$3
    shift; shift
    local ALL_SRC=$@
    local INCFILE="\$(DEPEND_DIR)/${CRATE_NAME}.define.mk"
    cat <<EOF
ALL_SRC_${CRATE_NAME}=${ALL_SRC}
MAIN_SRC_${CRATE_NAME}=${MAIN_SRC}
${INCFILE}: \$(ALL_SRC_${CRATE_NAME})
	./etc/mkdepend_define ${CRATE_TYPE} ${CRATE_NAME} \$< > \$@
-include ${INCFILE}
EOF
}

PRINT_RULE() {
    local CRATE_TYPE=$1
    local CRATE_NAME=$2
    local INCFILE="\$(DEPEND_DIR)/${CRATE_NAME}.rule.mk"
    cat <<EOF
${INCFILE}: \$(ALL_SRC_${CRATE_NAME})
	./etc/mkdepend_rule ${CRATE_TYPE} ${CRATE_NAME} \$^ > \$@
-include ${INCFILE}
EOF
}

PRINT_CRATE | while read LINE; do PRINT_DEFINE_INCLUDE ${LINE}; done
PRINT_CRATE | while read LINE; do PRINT_RULE ${LINE}; done
