#!/bin/bash

CRATE_TYPE=$1
CRATE_NAME=$2
MAIN_SRC=$3

case ${CRATE_TYPE} in
    RLIB)
        RLIB_NAME=$(basename $(rustc --crate-file-name "${MAIN_SRC}"))
        BIN_NAME=$(basename $(rustc --crate-file-name --test "${MAIN_SRC}"))
        cat <<EOF
DEBUG_${CRATE_NAME}=\$(DEBUG_RLIB_DIR)/${RLIB_NAME}
RELEASE_${CRATE_NAME}=\$(RELEASE_RLIB_DIR)/${RLIB_NAME}
DEBUG_${CRATE_NAME}test=\${DEBUG_BIN_DIR}/${BIN_NAME}test
RELEASE_${CRATE_NAME}test=\${RELEASE_BIN_DIR}/${BIN_NAME}test
EOF
        ;;
    BIN)
        BIN_NAME=$(basename $(rustc --crate-file-name "${MAIN_SRC}"))
        cat <<EOF
DEBUG_${CRATE_NAME}=\$(DEBUG_BIN_DIR)/${BIN_NAME}
RELEASE_${CRATE_NAME}=\$(RELEASE_BIN_DIR)/${BIN_NAME}
DEBUG_${CRATE_NAME}test=\${DEBUG_BIN_DIR}/${BIN_NAME}test
RELEASE_${CRATE_NAME}test=\${RELEASE_BIN_DIR}/${BIN_NAME}test
EOF
        ;;
    *)
        exit 1
        ;;
esac
