#!/bin/bash -ev

if [ "${TRAVIS_BRANCH}" != master ] ||
   [ "${TRAVIS_PULL_REQUEST}" != false ] ||
   [ "${TRAVIS_RUST_VERSION}" |= nightly ]; then
   exit 0
fi

cargo install ghp

ghp target/doc

git config user.name "Travis Documentation"
git config user.email "name@example.com"

git push -qf https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages 2>&1 > /dev/null
