#!/bin/bash -ev

CARGO_FLAGS="-v -j1"

cargo kcov ${CARGO_FLAGS} --all --coveralls

cargo build ${CARGO_FLAGS} --release --all

cargo run ${CARGO_FLAGS} --release --bin euler

cargo bench ${CARGO_FLAGS} --all

cargo doc ${CARGO_FLAGS} --all
